pipeline {
    agent any
    
    tools {nodejs "node"}
    
    stages {
        stage('Build') {
            steps {
                bat 'npm install'
            }
        }
        stage('Test') {
            steps {
                bat 'sh ./jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                bat 'sh ./jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                bat 'sh ./jenkins/scripts/kill.sh'
            }
        }
    }
}
